const currentDate = new Date();

const addresses = [
  {
    id: 1,
    street: 'Rua A',
    number: '1',
    complement: 'apartamento 1',
    neighborhood: 'centro',
    city: 'São Paulo',
    state: 'SP',
    country: 'Brasil',
    postal_code: '11111-000',
    user_id: 1,
    created_at: currentDate,
    updated_at: currentDate,
  },
  {
    id: 2,
    street: 'Rua B',
    number: '25',
    complement: 'apartamento 546',
    neighborhood: 'centro',
    city: 'Belo Horizonte',
    state: 'MG',
    country: 'Brasil',
    postal_code: '22222-000',
    user_id: 2,
    created_at: currentDate,
    updated_at: currentDate,
  },
  {
    id: 3,
    street: 'Rua C',
    number: '47',
    complement: 'apartamento 123',
    neighborhood: 'centro',
    city: 'São Paulo',
    state: 'SP',
    country: 'Brasil',
    postal_code: '33333-000',
    user_id: 3,
    created_at: currentDate,
    updated_at: currentDate,
  },
  {
    id: 4,
    street: 'Rua D',
    number: '1',
    complement: 'apartamento 867',
    neighborhood: 'centro',
    city: 'Rio de Janeiro',
    state: 'RJ',
    country: 'Brasil',
    postal_code: '44444-000',
    user_id: 4,
    created_at: currentDate,
    updated_at: currentDate,
  },
];

module.exports = addresses;
